// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Duxt

import 'package:jaspr_router/jaspr_router.dart';

import '../home/pages/index.dart' as page_homepage;
import '../demo/pages/index.dart' as page_demopage;

/// Generated routes from modules
final generatedRoutes = <Route>[
  Route(
    path: '/',
    builder: (context, state) {
      return const page_homepage.HomePage();
    },
  ),
  Route(
    path: '/demo',
    builder: (context, state) {
      return const page_demopage.DemoPage();
    },
  ),
];
