import 'dart:io';
import 'package:path/path.dart' as p;

/// Manages layout discovery and wrapping
///
/// Conventions (standard):
/// - layouts/default.dart -> Default layout for all pages
/// - layouts/admin.dart -> Named layout, use with `layout: 'admin'`
/// - layouts/error.dart -> Error page layout
class LayoutSystem {
  static final Map<String, String> _layouts = {};

  /// Scan layouts directory and register layouts
  static Future<void> scanLayouts(String projectDir) async {
    final layoutsDir = Directory(p.join(projectDir, 'layouts'));

    if (!layoutsDir.existsSync()) {
      return;
    }

    _layouts.clear();

    await for (final entity in layoutsDir.list()) {
      if (entity is File && entity.path.endsWith('.dart')) {
        final name = p.basenameWithoutExtension(entity.path);
        _layouts[name] = entity.path;
      }
    }
  }

  /// Get all registered layouts
  static Map<String, String> get layouts => Map.unmodifiable(_layouts);

  /// Check if a layout exists
  static bool hasLayout(String name) => _layouts.containsKey(name);

  /// Generate layouts registry code
  static String generateLayoutsCode(String projectDir) {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by Duxt');
    buffer.writeln('');
    buffer.writeln("import 'package:duxt/duxt.dart';");
    buffer.writeln('');

    // Import all layout files
    for (final entry in _layouts.entries) {
      final importPath = p.relative(entry.value, from: projectDir);
      buffer.writeln("import '../$importPath' as layout_${entry.key};");
    }

    buffer.writeln('');
    buffer.writeln('/// Wraps a page component with its layout');
    buffer.writeln('Component wrapWithLayout(String? layoutName, Component child) {');
    buffer.writeln('  final name = layoutName ?? "default";');
    buffer.writeln('  ');
    buffer.writeln('  switch (name) {');

    for (final name in _layouts.keys) {
      final className = '${_toPascalCase(name)}Layout';
      buffer.writeln("    case '$name':");
      buffer.writeln('      return layout_$name.$className(child: child);');
    }

    buffer.writeln('    default:');
    buffer.writeln('      return child;');
    buffer.writeln('  }');
    buffer.writeln('}');

    return buffer.toString();
  }

  static String _toPascalCase(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }
}
