import 'dart:async';

import 'manifest.dart';

/// Base interface for Duxt compiler plugins.
///
/// Plugins hook into the 4-phase build pipeline:
/// - Phase 1 (analyze): Inspect individual files via the Dart analyzer
/// - Phase 2 (manifest): Process the aggregated project manifest
/// - Phase 3 (transform): Generate code per component
/// - Phase 4 (entrypoints): Generate project-wide entry files
abstract class DuxtPlugin {
  /// Unique identifier for this plugin
  String get name;

  /// Phase 1: Analyze components in a single file.
  /// Called once per .dart file that contains components.
  FutureOr<void> analyze(ComponentAnalysis analysis) {}

  /// Phase 2: Process the full project manifest after all files are analyzed.
  /// Can modify route render modes, mark components, build dependency data.
  FutureOr<void> processManifest(DuxtManifest manifest) {}

  /// Phase 3: Generate code for a single component.
  /// Return null to skip, or a [TransformResult] with generated code.
  FutureOr<TransformResult?> transform(
    ComponentInfo component,
    DuxtManifest manifest,
  ) => null;

  /// Phase 4: Generate project-wide files (entry points, registries).
  FutureOr<List<GeneratedFile>> generateEntryPoints(
    DuxtManifest manifest,
  ) => [];
}

/// Result of a plugin transform for a single component.
class TransformResult {
  /// Generated Dart code to be written to the .duxt.dart file
  final String code;

  const TransformResult({required this.code});
}

/// A file to be generated by a plugin in Phase 4.
class GeneratedFile {
  /// Output path relative to the package root (e.g. 'web/islands/counter.client.dart')
  final String path;

  /// File contents
  final String content;

  const GeneratedFile({required this.path, required this.content});
}
